name: Flutter Web

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: any
        flutter-version: 3.x
        
    - name: Enable Flutter web 
      run: flutter config --enable-web 
      
    - name: Install dependencies
      run: flutter packages get
      
    - name: Build web
      run: flutter build web --release --web-renderer html 
      
    - name: Deploy
      uses: peaceiris/actions-marquee@v4
      with:
        github_token: ${{ secrets.token }}
        publish_dir: ./build/web